### ISSUE TITLE
[Windows] STRING to HEX to STRING data corruption

### ISSUE THREAD

**Issue by htmiel** [airext/openssl#5]
Converting a String to a hex string and the hex string back to String sometimes produces a String different from the original String.

This appears to happen randomly, and does not depend on the original String. This can be tested by using the exact same String each time. Most of the time it will work correctly, but sometimes not.

Testing appears to require opening and closing the app multiple times until the error is encountered.

Sample testing function:
```
function test_HEX_string():Boolean{
	
	//create a string
	inputString = "Hello world!"

	//convert to hex
	hex = OpenSSL.shared.hexFromString(inputString)

	//convert back to string
	outputString = OpenSSL.shared.hexToString(hex)

	//if the input and output strings are different, something was wrong
	if(inputString != outputString){
		Log("<cRed>test_HEX_string()")
		Log("<cRed>hexFromString() and hexToString() has produced an output different from input")
		return false
	}
	
	return true
}
```

**Comment by rozd** [comment]
Should be fixed in [0.2.2](https://github.com/airext/openssl/releases/tag/0.2.2)
