### ISSUE TITLE
[Windows] BYTES to HEX to BYTES freeze and crash

### ISSUE THREAD

**Issue by htmiel** [airext/openssl#6]
Converting a ByteArray to a hex string, adding a character to the hex string, and then attempting to convert the modified hex string back to a ByteArray causes the app to freeze and crash.

In case an error is encountered, the function should just return null, and not crash.

```
function test_HEX_bytes():Boolean{
	
	//load bytes
	bytes = fileUtils.getBytes(File.applicationDirectory.resolvePath("original bytes.bin"))

	//convert to hex
	hex = OpenSSL.shared.hexFromBytes(bytes)
	
	//add this to freeze and crash the app
	hex = hex + "x"

	//convert back to bytes
	bytes = OpenSSL.shared.hexToBytes(hex)

	return true
}
```

**Comment by rozd** [comment]
Should be fixed in [0.2.2](https://github.com/airext/openssl/releases/tag/0.2.2)
